In [5]:

import numpy as np

# 假设你的npy文件路径是 'path_to_your_npy_file.npy'
file_path = '/home/rzhou/Projects/Diffusion-TS/OUTPUT/inD_multi_18-29/ddpm_fake_inD_multi_18-29.npy'

# 使用numpy的load函数读取npy文件
fake_data = np.load(file_path)

# 现在，变量data包含了npy文件中的数据
# 你可以打印数据来查看内容，或者进行其他操作
print(fake_data)

[[[0.55268975 0.33130224 0.65990628 ... 0.27227208 0.61755574 0.56393848]
  [0.54990676 0.33053535 0.660566   ... 0.27228677 0.62312039 0.56595109]
  [0.55280809 0.33063932 0.65971282 ... 0.27069245 0.6107587  0.56018958]
  ...
  [0.61667973 0.33923648 0.6474378  ... 0.26752418 0.34162816 0.44311142]
  [0.61850087 0.33940691 0.6478079  ... 0.26699774 0.33261396 0.44007401]
  [0.61757654 0.33967045 0.65035352 ... 0.26809765 0.33690324 0.44170148]]

 [[0.54262234 0.35364507 0.66830964 ... 0.26686653 0.27048868 0.2868371 ]
  [0.54122843 0.3530658  0.66844395 ... 0.26688758 0.26944359 0.2868344 ]
  [0.54385594 0.35308576 0.66969177 ... 0.26701473 0.27182159 0.28809793]
  ...
  [0.57689902 0.34797224 0.71342415 ... 0.29118545 0.32638834 0.31648427]
  [0.57774173 0.34807864 0.7135047  ... 0.29103896 0.32820173 0.31769256]
  [0.57694894 0.34896283 0.71363431 ... 0.29101001 0.32813501 0.3171801 ]]

 [[0.74346854 0.78459504 0.61463946 ... 0.53134776 0.54567574 0.49285859]
  [0.74126185 0.784069

In [6]:
print(fake_data.shape)

(4002, 100, 10)


In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("/DATA1/rzhou/ika/multi_testcases/inD_multi_18-29.csv", header=0)
data = df.values
scaler = MinMaxScaler()
scaler = scaler.fit(data[:,1:])
scaler.inverse_transform(fake_data.reshape(-1, 10)).reshape(-1, 100, 10)


ValueError: Found array with dim 3. None expected <= 2.